apply plugin: 'groovy'
apply plugin: 'java-library'

group = 'cloud.wondrify'

ext {
    pomDescription = 'SASS/Compass Compiling support for the Asset-Pipeline library.'
}

configurations {
    provided
}
 
sourceSets {
    main {
        compileClasspath += configurations.provided
        resources{
            srcDir 'src/main/resources'
            srcDir 'src/main/ruby'
        }
    }
}

dependencies {
    compileOnly 'org.apache.groovy:groovy-all:4.0.22'
	api project(':asset-pipeline-core')
    // api 'log4j:log4j:1.2.17'
    // api 'org.yaml:snakeyaml:1.26'
    // api 'org.jruby:jruby:9.2.11.1'
	api 'org.jruby:jruby-complete:9.2.11.1'
    compile('com.bertramlabs.plugins:jruby-container:0.6.3') {
        exclude module: 'jruby-complete'
    }
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
}

tasks.register('console', JavaExec) {
  dependsOn('classes')
  mainClass = 'groovy.ui.Console'
  classpath = sourceSets.main.runtimeClasspath
}

test {
    testLogging {
        exceptionFormat = 'full'
        showStandardStreams = true
    }
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}
