version=5.2.0-M1
grailsVersion=8.0.0-M2
javaVersion=21
bootstrapCssVersion=5.3.3
closureCompilerVersion=v20260302
fluentHcVersion=4.5.14
graalvmVersion=24.1.2
# Core and plugins are compiled with Groovy 3 as they are used by the Gradle Plugin
groovy3Version=3.0.25
groovy4Version=4.0.32
httpcoreVersion=4.4.16
javaparserVersion=3.26.3
javetVersion=5.0.5
jettyVersion=12.1.10
jsassVersion=5.11.1
junit4Version=4.13.2
less4jVersion=1.17.2
less4jJsVersion=0.0.1
protobufVersion=3.21.12
rhinoVersion=1.8.0
servletApiVersion=6.1.0
slf4jVersion=2.0.18
spockVersion=2.3-groovy-4.0
springVersion=7.0.8
springBootVersion=4.1.0
webjarsLocatorVersion=0.59

org.gradle.warning.mode=none
