version=5.1.0-SNAPSHOT
grailsVersion=7.0.7
javaVersion=21
bootstrapCssVersion=5.3.3
closureCompilerVersion=v20250820
fluentHcVersion=4.5.14
graalvmVersion=24.1.2
# Core and plugins are compiled with Groovy 3 as they are used by the Gradle Plugin
groovy3Version=3.0.23
groovy4Version=4.0.25
httpcoreVersion=4.4.16
javaparserVersion=3.26.3
javetVersion=1.1.0
jettyVersion=11.0.24
jsassVersion=5.11.1
junit4Version=4.13.2
less4jVersion=1.17.2
less4jJsVersion=0.0.1
protobufVersion=3.21.12
rhinoVersion=1.8.0
servletApiVersion=6.0.0
slf4jVersion=2.0.16
spockVersion=2.3-groovy-4.0
springVersion=6.2.2
springBootVersion=3.4.2
webjarsLocatorVersion=0.59

org.gradle.warning.mode=none
