apply plugin: 'groovy'
apply plugin: 'java-library'

group = 'cloud.wondrify'

ext {
	pomDescription = 'JVM Asset Pipeline Servlet Adapter.'
}

repositories {
	mavenCentral()
}

configurations {
	provided
	doc.extendsFrom(runtime)
}

sourceSets {
	main {
		compileClasspath += configurations.provided
		groovy.srcDirs   += ['src/main/java']
		java.srcDirs      = []
	}
}

dependencies {

	api project(':asset-pipeline-core')

	implementation "org.apache.groovy:groovy:$groovy5Version"

	compileOnlyApi "jakarta.servlet:jakarta.servlet-api:$servletApiVersion"

	testImplementation "org.apache.httpcomponents:fluent-hc:$fluentHcVersion"
	testImplementation "org.apache.httpcomponents:httpcore:$httpcoreVersion"
	testImplementation "junit:junit:$junit4Version"
	testImplementation "org.eclipse.jetty:jetty-server:$jettyVersion"
	testImplementation "org.eclipse.jetty.ee11:jetty-ee11-servlet:$jettyVersion"
	testImplementation "org.eclipse.jetty.ee11:jetty-ee11-webapp:$jettyVersion"

	testRuntimeOnly "org.slf4j:slf4j-simple:$slf4jVersion"
}

test {
	testLogging {
		events('passed', 'skipped', 'failed')
		exceptionFormat = 'full'
		showStandardStreams = true
	}
}

tasks.register('console', JavaExec) {
	dependsOn('classes')
	mainClass = 'groovy.ui.Console'
	classpath = sourceSets.main.runtimeClasspath
}

apply {
	from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
	from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}