apply plugin: 'groovy'
apply plugin: 'java-library'

group = 'cloud.wondrify'

ext {
    pomDescription = 'Typescript Transpiler Extension for the JVM Based Asset-Pipeline.'
}

configurations {
    provided
}
sourceSets {
    main {
        compileClasspath += configurations.provided
    }
}

dependencies {
	api project(':asset-pipeline-core')
    api project(':jsx-asset-pipeline')
	compileOnly 'org.apache.groovy:groovy:4.0.22'
    api 'org.mozilla:rhino:1.7R4'
    // api 'log4j:log4j:1.2.17'

    testImplementation 'org.apache.groovy:groovy-all:4.0.22'
    testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
}

tasks.register('console', JavaExec) {
  dependsOn('classes')
  mainClass = 'groovy.ui.Console'
  classpath = sourceSets.main.runtimeClasspath
}

test {
    testLogging {
        exceptionFormat = 'full'
        showStandardStreams = true
    }
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}


