apply plugin: 'groovy'
apply plugin: 'java-library'
apply plugin: 'idea'

group = 'cloud.wondrify'

ext {
    pomDescription = 'GrooCSS Compiling support for the Asset-Pipeline library.'
    pomDevelopers = ['adamldavis': 'adamd@adamldavis.com']
}

configurations {
    provided
}
 
sourceSets {
    main {
        compileClasspath += configurations.provided
    }
}

dependencies {
    compileOnly 'org.apache.groovy:groovy-all:4.0.22'
    api project(':asset-pipeline-core')
	api "org.groocss:groocss:1.0-M1"

    testImplementation 'org.spockframework:spock-core:2.3-groovy-3.0'
}

tasks.register('console', JavaExec) {
  dependsOn('classes')
  mainClass = 'groovy.ui.Console'
  classpath = sourceSets.main.runtimeClasspath
}

test {
    testLogging {
        exceptionFormat = 'full'
        showStandardStreams = true
    }
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}
