apply plugin: 'groovy'
apply plugin: 'java-library'

group = 'cloud.wondrify'

ext {
	pomDescription = 'JVM Asset Pipeline Spring Boot Adapter.'
}

configurations {
	provided
	doc.extendsFrom(runtime)
}

sourceSets {
	main {
		compileClasspath += configurations.provided
		groovy.srcDirs   += ['src/main/java']
		java.srcDirs      = []
	}
}

dependencies {

	api project(':asset-pipeline-core')
	api project(':asset-pipeline-servlet')

	implementation "org.springframework:spring-beans:$springVersion"
	implementation "org.springframework:spring-context:$springVersion"
	implementation "org.springframework:spring-core:$springVersion"
	implementation "org.springframework:spring-web:$springVersion"
	implementation "org.springframework.boot:spring-boot:$springBootVersion"

	compileOnly "org.apache.groovy:groovy:$groovy5Version"
	compileOnly "org.slf4j:slf4j-api:$slf4jVersion"
}

tasks.register('console', JavaExec) {
	dependsOn('classes')
	mainClass = 'groovy.ui.Console'
	classpath = sourceSets.main.runtimeClasspath
}

apply {
	from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
	from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}